### DISCUSSION TITLE
Feature Request: Add support for load_aws_credentials when using a profile created using sso configure

### DISCUSSION THREAD

**Discussion by rileydakota** [duckdb/duckdb#12138] [Ideas]
When trying to use a profile created using `aws sso configure`, credentials don't get loaded, and requests to S3 fail with a 403 even when the profile is valid:

```toml
# ~/.aws/config
[profile my-sso-profile]
sso_session = my_sso_session
sso_account_id = 111122223333
sso_role_name = MyRole
```

```sql
# DuckDB

CALL load_aws_credentials('my-sso-profile', redact_secret = false)
  ;
┌──────────────────────┬──────────────────────────┬──────────────────────┬───────────────┐
│ loaded_access_key_id │ loaded_secret_access_key │ loaded_session_token │ loaded_region │
│       varchar        │         varchar          │       varchar        │    varchar    │
├──────────────────────┼──────────────────────────┼──────────────────────┼───────────────┤
│                      │                          │                      │ us-east-1     │

```

```sql 
# DuckDB

select * from read_json('s3://MY_VALID_BUCKET/*.gz');
HTTP Error: HTTP GET error on '/?encoding-type=url&list-type=2&prefix=REDACTED' (HTTP 403)
```
