### DISCUSSION TITLE
DuckDB with Iceberg HTTPCatalog via LakeKeeper

### DISCUSSION THREAD

**Discussion by manawasp** [duckdb/duckdb#17813] [Q&A] [answered]
Hello,

I try to figure out a potential configuration issue on my setup provided below via a docker-compose.yml . The issue may no be related to DuckDB but I struggle to know from the lakekeeper documentation if there is an issue there or not.

And when executing my python script if the compose up or not I get the same error, so it's a bit weird.

**docker-compose.yml**

```yaml
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-05-10T01-41-38Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  create-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set local http://minio:9000 minioadmin minioadmin;
        mc mb -p local/demo;
        mc policy set public local/demo;
        exit 0;
      "

  postgresql:
    image: bitnami/postgresql:16.6.0
    container_name: lakekeeper-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5432 -d postgres" ]
      interval: 2s
      timeout: 10s
      retries: 2
      start_period: 10s
    ports:
      - "5432:5432"

  catalog-migrate:
    image: quay.io/lakekeeper/catalog:latest-main
    depends_on:
      postgresql:
        condition: service_healthy
    command: migrate
    environment:
      - LAKEKEEPER__PG_ENCRYPTION_KEY=This-is-NOT-Secure!
      - LAKEKEEPER__PG_DATABASE_URL_READ=postgresql://postgres:postgres@lakekeeper-postgres:5432/postgres
      - LAKEKEEPER__PG_DATABASE_URL_WRITE=postgresql://postgres:postgres@lakekeeper-postgres:5432/postgres

  lakekeeper:
    image: quay.io/lakekeeper/catalog:latest-main
    container_name: lakekeeper
    depends_on:
      create-bucket:
        condition: service_completed_successfully
      catalog-migrate:
        condition: service_completed_successfully
    ports:
      - "8181:8181"
    environment:
      - LAKEKEEPER__PG_ENCRYPTION_KEY=This-is-NOT-Secure!
      - LAKEKEEPER__PG_DATABASE_URL_READ=postgresql://postgres:postgres@lakekeeper-postgres:5432/postgres
      - LAKEKEEPER__PG_DATABASE_URL_WRITE=postgresql://postgres:postgres@lakekeeper-postgres:5432/postgres
      - LAKEKEEPER_CATALOGS_DEMO_TYPE=iceberg
      - LAKEKEEPER_CATALOGS_DEMO_WAREHOUSE=s3://demo/
      - LAKEKEEPER_CATALOGS_DEMO_AUTHORIZATION_TYPE=none
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
      - RUST_LOG=info
    command: [ "serve" ]
    healthcheck:
      test: [ "CMD", "/home/nonroot/lakekeeper", "healthcheck" ]
      interval: 1s
      timeout: 10s
      retries: 3
      start_period: 3s

  catalog-bootstrap:
    image: curlimages/curl
    container_name: lakekeeper-tos
    depends_on:
      lakekeeper:
        condition: service_healthy
    restart: "no"
    command:
      - -w
      - "%{http_code}"
      - "-X"
      - "POST"
      - "-v"
      - "http://lakekeeper:8181/management/v1/bootstrap"
      - "-H"
      - "Content-Type: application/json"
      - "--data"
      - '{"accept-terms-of-use": true}'
      - "-o"
      - "/dev/null"

  init-datalakehouse:
    image: curlimages/curl
    container_name: lakekeeper-demo-warehouse-init
    depends_on:
      lakekeeper:
        condition: service_healthy
    restart: "no"
    command:
      - -w
      - "%{http_code}"
      - "-X"
      - "POST"
      - "-v"
      - "http://lakekeeper:8181/management/v1/warehouse"
      - "-H"
      - "Content-Type: application/json"
      - "--data"
      - "@create-demo-warehouse.json"
      - "-o"
      - "/dev/null"
      - "--fail-with-body"
    volumes:
      - ./create-demo-warehouse.json:/home/curl_user/create-demo-warehouse.json


volumes:
  minio-data:
```

**create-demo-warehouse.json**

```json
{
  "warehouse-name": "demo",
  "project-id": "00000000-0000-0000-0000-000000000000",
  "storage-profile": {
    "type": "s3",
    "bucket": "demo",
    "assume-role-arn": null,
    "endpoint": "http://minio:9000",
    "region": "local-01",
    "path-style-access": true,
    "flavor": "minio",
    "sts-enabled": true
  },
  "storage-credential": {
    "type": "s3",
    "credential-type": "access-key",
    "aws-access-key-id": "minioadmin",
    "aws-secret-access-key": "minioadmin"
  }
}
```

**use_catalog.py**

```python
import duckdb

conn = duckdb.connect(database=":memory:")
conn.execute("INSTALL httpfs; LOAD httpfs;")
conn.execute("INSTALL iceberg; LOAD iceberg;")

conn.execute("""
SET s3_endpoint='minio:9000';
SET s3_region='local-01';
SET s3_access_key_id='minioadmin';
SET s3_secret_access_key='minioadmin';
SET s3_use_ssl=false;
SET s3_url_style='path';
""")

conn.execute("""
    ATTACH 'demo' AS demo (
        TYPE ICEBERG,
        CATALOG_TYPE REST,
        ENDPOINT 'http://localhost:8181',
        WAREHOUSE 's3://demo/'
    );
""")
```

Finally:

 `docker compose up --build --force-recreate`

Then

```sh
$ uv venv
$ source venv/bin/activate
(venv) $ uv pip install duckdb
(venv) $ python use_catalog.py
```

And finally I got the error:

```sh
(venv) $ python use_catalog.py 
Traceback (most recent call last):
  File ".../use_catalog.py", line 18, in <module>
    conn.execute("""
    ~~~~~~~~~~~~^^^^
        ATTACH 'demo' AS demo (
        ^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        );
        ^^
    """)
    ^^^^
duckdb.duckdb.Error: AUTHORIZATION_TYPE is 'oauth2', yet no 'secret' was provided, and no client_id+client_secret were provided. Please provide one of the listed options or change the 'authorization_type'.
```

And when calling the catalog:

```sh
$ curl "http://localhost:8181/catalog/v1/config?warehouse=demo" | jq  
{
  "overrides": {
    "uri": "http://localhost:8181/catalog"
  },
  "defaults": {
    "prefix": "350d8fda-420b-11f0-b25a-b73e93df6e7e",
    "rest-page-size": "100"
  },
  "endpoints": [
    "GET /v1/config",
    "GET /v1/{prefix}/namespaces",
    "HEAD /v1/{prefix}/namespaces/{namespace}",
    "POST /v1/{prefix}/namespaces",
    "GET /v1/{prefix}/namespaces/{namespace}",
    "DELETE /v1/{prefix}/namespaces/{namespace}",
    "POST /v1/{prefix}/namespaces/{namespace}/properties",
    "GET /v1/{prefix}/namespaces/{namespace}/tables",
    "POST /v1/{prefix}/namespaces/{namespace}/tables",
    "GET /v1/{prefix}/namespaces/{namespace}/tables/{table}",
    "POST /v1/{prefix}/namespaces/{namespace}/tables/{table}",
    "DELETE /v1/{prefix}/namespaces/{namespace}/tables/{table}",
    "HEAD /v1/{prefix}/namespaces/{namespace}/tables/{table}",
    "GET /v1/{prefix}/namespaces/{namespace}/tables/{table}/credentials",
    "POST /v1/{prefix}/tables/rename",
    "POST /v1/{prefix}/namespaces/{namespace}/register",
    "POST /v1/{prefix}/namespaces/{namespace}/tables/{table}/metrics",
    "POST /v1/{prefix}/transactions/commit",
    "POST /v1/{prefix}/namespaces/{namespace}/views",
    "GET /v1/{prefix}/namespaces/{namespace}/views",
    "GET /v1/{prefix}/namespaces/{namespace}/views/{view}",
    "POST /v1/{prefix}/namespaces/{namespace}/views/{view}",
    "DELETE /v1/{prefix}/namespaces/{namespace}/views/{view}",
    "HEAD /v1/{prefix}/namespaces/{namespace}/views/{view}",
    "POST /v1/{prefix}/views/rename"
  ]
}
```

- https://duckdb.org/docs/stable/core_extensions/iceberg/iceberg_rest_catalogs#lakekeeper

If you any idea thanks! :pray:
