### ISSUE TITLE
Integer parameters sometimes become varchar when using python dbapi

### ISSUE THREAD

**Issue by machow** [duckdb/duckdb#2972]
#### What happens?

Currently, python users interfacing with postgresql via dbapi drivers like `psycopg2` can parameterize queries like...

```
-- %s is the parameter
SELECT %s
```

and if they pass an int like `1` as a parameter, it is equivalent to...

```
-- note 1's pg_typeof here would be integer, rather than varchar
SELECT 1
```

The implementation of this behavior is discussed in the [DBAPI pep 249 here](https://www.python.org/dev/peps/pep-0249/#type-objects-and-constructors).

Quick Notes: 

* The style used to define parameters may vary across dbapi implementations, but tools like sqlalchemy abstract away the need for users to worry about this.
* I have a backend implementation of duckdb working on a tool called siuba (https://github.com/machow/siuba/pull/380), which essentially translates pandas methods to duckdb, but there are some edge cases where an int could go in, but a string (or object dtype) could come out..!

#### To Reproduce

```python
import psycopg2
import duckdb

# setup postgres
pg_con = psycopg2.connect(database="postgres", user="postgres", password="", port=5432, host="localhost")
pg_curs = pg_con.cursor()

# setup duckdb
duck_con = duckdb.connect(":memory:")


# queries ----

# integer
pg_curs.execute("SELECT pg_typeof(%s)", (1,))
pg_curs.fetchone()

# varchar
duck_con.execute("SELECT pg_typeof(?)", (1,)).fetchone()
```

Here is the docker compose I used to setup postgres:

<details>

```
version: '3.1'

services:

  db_mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: "public"
    ports:
      - 3306:3306
    # by default, mysql rounds to 4 decimals, but tests require more precision
    command: --div-precision-increment=30

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
        - 5432:5432
```

</details>

#### Environment (please complete the following information):
 - OS: OSX 11.3.1
 - DuckDB Version: 0.3.2
 - DuckDB Client: Python

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**
