### ISSUE TITLE
ARM JDBC binaries (Graviton, Apple Silicon, etc)

### ISSUE THREAD

**Issue by pshirshov** [duckdb/duckdb#941]
Hi! 

Thanks for the nice library! It works great with GraalVM `native-image`

It would be very good to have a ready-to-use jar supporting various ARM flavors, especially Linux+Graviton and MacOS+Apple Silicon. Could you please build ship the corresponding libraries as you do with x86 ones?

**Comment by hannesmuehleisen** [comment]
Certainly. Which exact ARM flavours are you referring to? You could also help by telling us the values of `System.getProperty("os.name")` and `System.getProperty("os.arch")` on those platforms.

**Comment by pshirshov** [comment]
Apple Silicon and Amazon Graviton.

Graviton seems to be a pretty standard ARM:

```
jshell> System.getProperty("os.name")
$1 ==> "Linux"

jshell> System.getProperty("os.arch")
$2 ==> "aarch64"
```

I don't have an Apple Silicon machine yet, once I get one I'll post the details here.

**Comment by hannesmuehleisen** [comment]
We already build on aarch64 so I just need to enable the JDBC build on that platform. Wish me luck.

**Comment by pshirshov** [comment]
Thanks!

**Comment by space55** [comment]
Hello,

I was just wondering if this bug has been fixed? I'm trying to install the Python 0.2.2 version on an AWS Graviton instance, and it's failing to run because of a missing symbol: `__aarch64_ldadd4_relax`.
I assume it's related?

Thanks!

**Comment by chilanglr** [comment]
Any chance we can get osx_arm64 binaries published? 
It looks like it's building fine on M1 Mac.
Thanks

**Comment by pgabry** [comment]
trying to get this one working: https://blog.chage.cc/2021/06/07/duckdb-jdbc-driver-issue-on-m1.html

**Comment by hannes** [comment]
We now have OSX ARM JDBC binaries

**Comment by wizzard0** [comment]
ummm... Did osx arm jdbc binaries got published as part of 0.3.3? Don't see any osx jdbc files in release files 🤔

**Comment by hannes** [comment]
There seems to have been a CI issue :/

**Comment by erikcw** [comment]
Would love a linux arm release for the python package as well.  `pip install duckdb` adds over an hour to my Docker build process on github actions:

```yaml
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.prep.outputs.tags }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
```
